// <auto-generated />
using System;
using AutoMapperTutorial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoMapperTutorial.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190904082410_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoMapperTutorial.Models.Barat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nev");

                    b.HasKey("Id");

                    b.ToTable("Barat");
                });

            modelBuilder.Entity("AutoMapperTutorial.Models.Ember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("KeresztNev");

                    b.Property<decimal>("Kor");

                    b.Property<string>("VezetekNev");

                    b.HasKey("Id");

                    b.ToTable("Emberek");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ember");

                    b.HasData(
                        new
                        {
                            Id = new Guid("774d5bf8-d080-4a48-9e9a-bfa13a286781"),
                            KeresztNev = "József",
                            Kor = 30m,
                            VezetekNev = "Kovács"
                        });
                });

            modelBuilder.Entity("AutoMapperTutorial.Models.Leszarmazott", b =>
                {
                    b.HasBaseType("AutoMapperTutorial.Models.Ember");

                    b.Property<Guid?>("BaratId");

                    b.Property<string>("HajSzin");

                    b.Property<string>("SzemSzin");

                    b.HasIndex("BaratId");

                    b.HasDiscriminator().HasValue("Leszarmazott");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85474139-82ac-4d23-957d-255f7e799687"),
                            KeresztNev = "Ferenc",
                            Kor = 6m,
                            VezetekNev = "Kovács",
                            HajSzin = "Barna",
                            SzemSzin = "Kék"
                        });
                });

            modelBuilder.Entity("AutoMapperTutorial.Models.Leszarmazott", b =>
                {
                    b.HasOne("AutoMapperTutorial.Models.Barat", "Barat")
                        .WithMany()
                        .HasForeignKey("BaratId");
                });
#pragma warning restore 612, 618
        }
    }
}
